### ISSUE TITLE
non-contiguous tensor issue on style_interpolate_transfer.py

### ISSUE THREAD

**Issue by newsbubbles** [YangXingchao/makeup-priors#3]
```
creating the FLAME Decoder
Traceback (most recent call last):
  File "/home/.../code/makeup-priors/style_interpolate_transfer.py", line 77, in <module>
    uv_ret = compute_uv_render(mm_ret, rast_uv, tri, rend_uv_mask)
  File "/home/.../code/makeup-priors/utils/render_util.py", line 138, in compute_uv_render
    diff, _ = dr.interpolate(mm_ret['diff'], rast, tri)
  File "/home/.../.local/lib/python3.10/site-packages/nvdiffrast/torch/ops.py", line 474, in interpolate
    return _interpolate_func.apply(attr, rast, tri)
  File "/home/.../.local/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/.../.local/lib/python3.10/site-packages/nvdiffrast/torch/ops.py", line 413, in forward
    out, out_da = _get_plugin().interpolate_fwd(attr, rast, tri)
RuntimeError: interpolate_fwd_da(): Inputs attr, rast, tri must be contiguous tensors
```
Apparently render_util on interpolate is sending these inputs and they are not contiguous? or they are just none? not sure.

Is this a version fix or something of the like?

**Comment by YangXingchao** [comment]
how about trying `mm_ret['diff'].contiguous()`?
